config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#toppage'
  devise_for :users
  resources :messages, only: [:toppage, :index, :new, :create, :edit, :destroy, :show, :update] do
    resources :comments, only: [:create]
  end
  resources :categories, only: [:show]
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :users
  has_many :messages
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :text, presence: true
  # mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :category
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    messages_path 
  end

  def after_sign_out_path_for(resource)
    root_path 
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    # @categories = Category.all
    @category = Category.find(params[:id])
    # binding.pry
    @messages = @category.messages.includes(:user)
    # @messages = Category.where(category_id: params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/messages/#{comment.message.id}" 
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_current_user

  def toppage
  end

  def index
    @messages = Message.all
    @messages = @messages.includes(:user).order("created_at DESC")
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.create(message_params)
    redirect_to messages_path
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to messages_path
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    message = Message.find(params[:id])
    message.update(message_params)
    redirect_to messages_path
  end

  def show
    @message = Message.find(params[:id])
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
  end

  private

  def message_params
    params.require(:message).permit(:category_id, :image, :text).merge(user_id: current_user.id)
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController  < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < Users::ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to messages_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.haml
.wrapper
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .header
      = render "messages/header"
    .main
      = render "messages/side_bar"
      .user_bar
        - @messages.each do |message|
          = render partial: "messages/user_bar", locals: { message: message }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title foodshare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_header.html.haml
.header
  .header-contents
    .contents-left
      .left-items
        %p.left-items__title
          = link_to "FoodShare", root_path, class: 'btn'
        %p.left-items__form
          = link_to "新規投稿", new_message_path, class: 'btn'
    .contents-right
      .right-items
        %p.right-items__mypage
          = link_to current_user.name, edit_user_path(current_user), class: 'btn'
        %p.right-items__icon
          = image_tag(current_user.image, :size =>'50x50')
        %p.right-items__out
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'

app/views/messages/_side_bar.html.haml
.side-bar
  .top
    = link_to "/categories/1" do
      %p.trim-image-to-circle01
    = link_to "/categories/2" do
      %p.trim-image-to-circle02
  .middle
    = link_to "/categories/3" do
      %p.trim-image-to-circle03
    = link_to "/categories/4" do
      %p.trim-image-to-circle04
  .bottom
    = link_to "/categories/5" do
      %p.trim-image-to-circle05
    = link_to "/categories/6" do
      %p.trim-image-to-circle06

app/views/messages/_user_bar.html.haml
.col-xs-4
  .card.border-dark.mb-3{:style => "max-width: 18rem;"}
    .card-header.bg-transparent.border-dark 
      = message.category.meal_category
    = link_to  "/messages/#{message.id}" do
      .card-body.text-dark
        - if message.text.present?
          %h5.card-image
            = image_tag(message.image, :size =>'170x150') if message.image.present?
          %p.card-text 
            = simple_format(message.text)
    .card-footer.bg-transparent.border-dark
      = message.user.name
      %ul.icons
        - if user_signed_in? && current_user.id == message.user.id
          = link_to edit_message_path(message.id), class:"btn--edit" do
            = icon('far', 'edit', class: "icons__btn")
          = link_to "/messages/#{message.id}", method: :delete, class:"btn--delete" do
            = icon('fas', 'trash-alt', class: "icons__btn")

app/views/messages/edit.html.haml
.contents
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .container__inner.clearfix
      = form_with(model: @message, local: true) do |form|
        %h4
          編集
        = form.collection_select :category_id, Category.all, :id, :meal_category, {class: "select"}
        = form.text_field :image, placeholder: "Image Url", class: 'photo'
        = form.text_area :text, placeholder: "text" , rows: "10" , class: 'text'
        = form.submit "SEND" , class: 'btn-send'
        = link_to "トップページに戻る", messages_path, class:'btn'

app/views/messages/index.html.haml
.wrapper
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .header
      = render "header"
    .main
      = render "side_bar"
      .user_bar
        - @messages.each do |message|
          = render partial: "user_bar", locals: { message: message }

app/views/messages/new.html.haml
.contents
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .container__inner.clearfix
      = form_with(model: @message, local: true) do |form|
        %h3
          今何食べたい？
        = form.collection_select :category_id, Category.all, :id, :meal_category, {class: "select"}
        = form.text_field :image, placeholder: "Image Url", class: 'photo'
        = form.text_area :text, placeholder: "text" , rows: "10" , class: 'text'
        = form.submit "SEND" , class: 'btn-send'
        = link_to "トップページに戻る", messages_path, class:'btn'

app/views/messages/show.html.haml
.details
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .details__inner.clearfix
      .card.border-dark.mb-3
        .card-header.bg-transparent.border-dark
          = @message.category.meal_category
        .card-body.text-dark
          %h5.card-image
            = image_tag(@message.image, size: 200) if @message.image.present?
          %p.card-text 
            = simple_format(@message.text)
        .card-footer.bg-transparent.border-dark
          = @message.user.name
      .comment-detail
        %h4 
          コメント一覧
        .comments
          - if @comments
            - @comments.each do |comment|
              %p
                %strong
                  = comment.user.name + "："
                = comment.text
        .comment-form
          - if current_user
            = form_with(model: [@message, @comment], local: true) do |form|
              = form.text_area :text, placeholder: " コメントする", rows: "2", class: "comment-text"
              = form.submit "SEND", class: 'btn-send-comment'
          - else
            %strong
              %p 
                ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
        = link_to "トップページに戻る", messages_path, class:'btn'

app/views/messages/toppage.html.haml
.wrapper
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .toppage-Contents
      .top-content
        FoodShare
      .middle-content
        .text
          .title 今何食べたい？でツナガル世界
          Foodshare（フードシェア）は、
          %br
          今食べたいものを共有できる新感覚サービスです。
          %br
          今食べたくて仕方ないものがあるあなたも
          %br
          今日何食べようか迷っているあなたも
          %br
          めくるめく食の世界へ
        .signBox
          .signUpBox
            = link_to "新規会員登録", " /users/sign_up", class:'sign-btn'
          .signInBox
            = link_to "ログイン", " /users/sign_in", class:'sign-btn'
      .bottom-content

app/views/users/edit.html.haml
#account-page.account-page
  %video{:autoplay => "", :loop => "", :muted => "", :src => "https://assets.mixkit.co/videos/2445/2445-1080.mp4"}
  .overlay
    .account-page__inner.clearfix
      .account-page__inner--left.account-page__header
        %h2 Edit Account
        %h5 アカウントの編集
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
        = link_to "トップページに戻る", root_path, class: 'btn'
      .account-page__inner--right.user-form
        = form_for(current_user) do |f|
          .field
            .field-label
              = f.label :name
            .field-input
              = f.text_field :name, autofocus: true
          .field
            .field-label
              = f.label :image
              %i (画像URLを入力)
            .field-input
              = f.text_field :image
          .field
            .field-label
              = f.label :email
            .field-input
              = f.email_field :email
          .actions
            = f.submit "Update", class: 'btn-update'